version: '3.1'

services:

  postgres-server:    # The Postgres Database Service
    image: postgres:latest
    restart: always
    environment:   # Username, password and database name variables
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
    env_file:
      - .env
    volumes:
       - PG_DATA:/var/lib/postgresql/data #data storage


  zabbix-server:     # The main Zabbix Server Software Service
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    restart: always
    environment:   # The Postgres database value variable
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
      ZBX_HISTORYSTORAGETYPES: ${ZBX_HISTORYSTORAGETYPES} #Zabbix configuration variables
      ZBX_DEBUGLEVEL: ${ZBX_DEBUGLEVEL}
      ZBX_HOUSEKEEPINGFREQUENCY: ${ZBX_HOUSEKEEPINGFREQUENCY}
      ZBX_MAXHOUSEKEEPERDELETE: ${ZBX_MAXHOUSEKEEPERDELETE}
    env_file:
      - .env
    depends_on:
      - postgres-server
    volumes:  # Volumes for scripts and related files you can add
      - ZABBIX_ALERTSCRIPTS:/usr/lib/zabbix/alertscripts


  zabbix-web:    # The main Zabbix web UI or interface
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
    restart: always
    environment:  # Postgre database variables
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}  # Zabbix related and Php variables
      ZBX_POSTMAXSIZE: ${ZBX_POSTMAXSIZE}
      PHP_TZ: ${PHP_TZ}
      ZBX_MAXEXECUTIONTIME: ${ZBX_MAXEXECUTIONTIME}
    env_file:
      - .env
    depends_on:
      - postgres-server
      - zabbix-server
    ports:    # Port where Zabbix UI is available
      - 80:80
    command: >
        /bin/bash -c "sudo mkdir -p /var/lib/apt/lists/partial && sudo chmod 755 /var/lib/apt/lists/partial && apt-get update && apt-get install -y nginx-full && nginx -g 'daemon off;'"


  zabbix-agent:   # Zabbix agent service that tracks usage and send to zabbix server
    image: zabbix/zabbix-agent:latest
    privileged: true   #access mode for allowing resource access
    network_mode: "host"
    restart: unless-stopped
    environment:
      - ZBX_SERVER_HOST=127.0.0.1 #the IP/Dns of Zabbix server
    env_file:
      - .env


  adminer:  #Optional for accessing databases
    image: adminer
    restart: always
    ports:
      - 8080:8080


  grafana-xxl:  #optional more functional and creative UI
    image: monitoringartist/grafana-xxl:latest
    ports:
     - 3000:3000
    volumes:
     - GRAFANA_CONFIG:/etc/grafana
     - GRAFANA_DATA:/var/lib/grafana


volumes:
  PG_DATA:
  ZABBIX_ALERTSCRIPTS:
  GRAFANA_CONFIG:
  GRAFANA_DATA: