version: '3.1'

services:

  postgres-server:    # The Postgres Database Service
    image: postgres:latest
    restart: always
    environment:   # Username, password database name and more variables
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
    env_file:
      - .env
    volumes:
       - PG_DATA:/var/lib/postgresql/data #data storage


  zabbix-server:     # The main Zabbix Server Software Service
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    restart: always
    environment:  
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
      ZBX_HISTORYSTORAGETYPES: ${ZBX_HISTORYSTORAGETYPES} 
      ZBX_DEBUGLEVEL: ${ZBX_DEBUGLEVEL}
      ZBX_HOUSEKEEPINGFREQUENCY: ${ZBX_HOUSEKEEPINGFREQUENCY}
      ZBX_MAXHOUSEKEEPERDELETE: ${ZBX_MAXHOUSEKEEPERDELETE}
    env_file:
      - .env 
    depends_on:
      - postgres-server
    ports:
      - 10051:10051
    volumes:  # Volumes for scripts and related files
      - ZABBIX_ALERTSCRIPTS:/usr/lib/zabbix/alertscripts


  zabbix-web:    # The main Zabbix web UI or interface
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
    restart: always
    environment:  # Postgre database variables
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}  # Zabbix related and Php variables
      ZBX_POSTMAXSIZE: ${ZBX_POSTMAXSIZE}
      PHP_TZ: ${PHP_TZ}
      ZBX_MAXEXECUTIONTIME: ${ZBX_MAXEXECUTIONTIME}
    env_file:
      - .env
    depends_on:
      - postgres-server
      - zabbix-server
    ports:    # Port where Zabbix UI is available
      - 8090:80


  grafana:  
    image: grafana/grafana:latest
    ports:
     - 3000:3000
    command: >
     bash -c "grafana-cli plugins install alexanderzobnin-zabbix-app && systemctl restart grafana-server"
    environment:
     - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
     - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=alexanderzobnin-zabbix-app
     - allow_loading_unsigned_plugins=alexanderzobnin-zabbix-app
    volumes:
     - GRAFANA_CONFIG:/etc/grafana
     - GRAFANA_DATA:/var/lib/grafana


volumes:
  PG_DATA:
  ZABBIX_ALERTSCRIPTS:
  GRAFANA_CONFIG:
  GRAFANA_DATA: